server {
    listen 80;
    server_name the-technical-office-for-landscaping-works.com www.the-technical-office-for-landscaping-works.com;
    
    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name the-technical-office-for-landscaping-works.com www.the-technical-office-for-landscaping-works.com;
    root /var/www/public;

    # SSL certificates paths
    ssl_certificate /etc/letsencrypt/live/the-technical-office-for-landscaping-works.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/the-technical-office-for-landscaping-works.com/privkey.pem;

    # SSL optimization protocols
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
